---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cultura/consorcio.cultura.org.br/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
